define([
    'jquery',
    'underscore',
    'backbone',
    'src/eventbus',
    'src/models',
    'src/views',
    'src/collections',
    'src/utilities',
], function ($, _, Backbone, eventbus, models, views, collections, utils) {
    console.log($);
    console.log(_);
    console.log(eventbus);
    console.log(Backbone);
    console.log(models.Film);
    console.log(views.FilmView);
    console.log(collections.Films);
    console.log(utils);
});
